### ISSUE TITLE
FAILED courgette.runtime.CourgetteTestFailureException 

### ISSUE THREAD

**Issue by sharti** [prashant-ramcharan/courgette-jvm-example#10]
Lately, I have been seeing this issue with courgette-jvm. None of my tests are running it just complains :

> Task :runNonParallelTests

Installation includes of installing and getting the local license server up and running. failed.
courgette.runtime.CourgetteTestFailureException: Installation includes of installing and getting the local license server up and running. failed.

com.flexnetls.automation.runners.NonParallelRunner > courgette.api.junit.Courgette.Installation includes of installing and getting the local license server up and running. FAILED
    courgette.runtime.CourgetteTestFailureException 

the version I have tried with are 5.12.0 and the latest. Can you please help on this?

**Comment by prashant-ramcharan** [comment]
Hello, 

`CourgetteTestFailureException` is thrown when your tests fail. 

So `Installation includes of installing and getting the local license server up and running` is the name of the failing scenario / feature?
