### ISSUE TITLE
How fix java.lang.ClassNotFoundException: Files\Git\cmd;;/

### ISSUE THREAD

**Issue by BAMTIUIP** [prashant-ramcharan/courgette-jvm-example#11]
![IMG_20230926_203608](https://github.com/prashant-ramcharan/courgette-jvm-example/assets/36363375/2b29b0e5-f094-4099-8eee-b47a6412bcaa)

How fix this?

**Comment by prashant-ramcharan** [comment]
This does not seem related to Courgette.

Please try checking your project dependancies or resetting your IDE cache etc..
