### ISSUE TITLE
run mutiple time for each SCENARIO

### ISSUE THREAD

**Issue by weitun** [prashant-ramcharan/courgette-jvm-example#5]
As shown in the example, I create my cucumber test as 
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 3,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = false,
        showTestOutput = true,
        reportTargetDir = "target",
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources",
                glue = {"com.discover.fdns.ods.qa"},
                plugin = {
                        "pretty",
                        "json:cucumber-test-report.json",
                        "html:cucumber-test-report",
                        "junit:cucumber-test-result.xml"}
        ))
public class RunCukesTest {

}

however, after I finished the test, for every scenario, it run 5 times. I attached the test result. Could you please give some suggestion?

[Courgette-JVM Report.pdf](https://github.com/prashant-ramcharan/courgette-jvm-example/files/2676545/Courgette-JVM.Report.pdf)

**Comment by prashant-ramcharan** [comment]
Can you paste your build.gradle file?

**Comment by weitun** [comment]
thanks a lot. This is my build.gradle.
------------------------------------------------------------------------------------------
buildscript {
    ext {
        springbootVersion = '2.1.0.RELEASE'
        cukesVersion = '2.3.1'
        dependencyManagementPlugin = '0.5.3.RELEASE'
        springFrameworkVersion = '5.0.10.RELEASE'
    }
    repositories {
        mavenLocal()
        jcenter()

    }
    dependencies {
        classpath("com.netflix.nebula:gradle-lint-plugin:8.3.1")
        classpath("com.netflix.nebula:gradle-info-plugin:3.6.0")
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springbootVersion}")
        classpath("io.spring.gradle:dependency-management-plugin:${dependencyManagementPlugin}")
    }
}
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

repositories {
    mavenLocal()
    jcenter()
}

sourceCompatibility = 1.8

dependencies {
    compile("org.springframework.boot:spring-boot-starter:${springbootVersion}") {
        exclude group: 'org.apache.logging.log4j', module: 'log4j-to-slf4j'
    }
    compile("org.springframework:spring-context:${springFrameworkVersion}")
    compile group: 'org.springframework', name: 'spring-tx', version: '5.0.10.RELEASE'
    compile("org.yaml:snakeyaml:1.19")

    compile("io.cucumber:cucumber-core:${cukesVersion}")
    compile("io.cucumber:cucumber-junit:${cukesVersion}")
    compile("io.cucumber:cucumber-java:${cukesVersion}")
    compile("io.cucumber:cucumber-spring:${cukesVersion}")

    testCompile('io.github.prashant-ramcharan:courgette-jvm:2.4.0') {
        exclude group: 'io.cucumber'
    }
    compile("org.apache.logging.log4j:log4j-slf4j-impl:2.10.0")
    compile("org.projectlombok:lombok:1.16.16")
    compile("commons-io:commons-io:2.6")
    compile("org.awaitility:awaitility:3.1.1")

    compile("org.apache.avro:avro:1.7.7")

    compileOnly('org.springframework.boot:spring-boot-configuration-processor:2.0.1.RELEASE')

    testCompile("org.assertj:assertj-core:3.10.0")
    testCompile("org.springframework:spring-test:${springFrameworkVersion}")
    testCompile("junit:junit:4.12")
    testCompile("org.mockito:mockito-core:2.19.0")
}

tasks.withType(Test) {
    systemProperties = System.getProperties()
    systemProperties.remove("java.endorsed.dirs") // needs to be removed from Java 9
}

task regressionSuite(type: Test) {
    include '**/RunCukesTest.class'

    outputs.upToDateWhen { false }
}

**Comment by prashant-ramcharan** [comment]
Remove the cucumber dependencies from your build.gradle.

````gradle
compile("io.cucumber:cucumber-core:${cukesVersion}")
compile("io.cucumber:cucumber-junit:${cukesVersion}")
compile("io.cucumber:cucumber-java:${cukesVersion}")
compile("io.cucumber:cucumber-spring:${cukesVersion})
````

Just keep the courgette dependency in your build.gradle.

**Comment by weitun** [comment]
thanks and I tried but it is still same. Each scenario runs 5 times. Any more suggestion please?

**Comment by prashant-ramcharan** [comment]
Do you have any cucumber runners in your project in addition to the courgette runner?

Please share your project or any project that can reproduce this issue and il take a look.

**Comment by weitun** [comment]
thanks a lot and I made a quick sample project with intellij. And you can run RunCukeTest and it shows your report in the target folder.
[general-automation.zip](https://github.com/prashant-ramcharan/courgette-jvm-example/files/2682596/general-automation.zip)

**Comment by weitun** [comment]
report is here
[courgette-report.zip](https://github.com/prashant-ramcharan/courgette-jvm-example/files/2682600/courgette-report.zip)

**Comment by weitun** [comment]
thanks a lot for the help

**Comment by prashant-ramcharan** [comment]
Place your feature files in a sub directory (_any name_) within resources.

<img width="878" alt="screenshot 2018-12-15 at 21 37 43" src="https://user-images.githubusercontent.com/2563149/50047667-0b94f180-00b2-11e9-8a99-9691f699af3c.png">

**Comment by weitun** [comment]
nice, it works. Any comments about why? Do you think it is worth of fixing it? I mean should it allow feature files in resources folder?

**Comment by prashant-ramcharan** [comment]
This does not require a fix as it's not broken - Courgette does not find or copy feature files, it uses Cucumber for this.

It simply means, your feature files are copied to the classpath twice.  

Having feature files in the resources/some-folder is common practice. Take a look at https://github.com/cucumber/cucumber-java-skeleton

And here: https://docs.cucumber.io/gherkin/step-organization/#how-cucumber-finds-your-features-and-step-definitions

**Comment by weitun** [comment]
nice and thanks
