### ISSUE TITLE
Any Plans when are you integrating Courgette with Allure Reports

### ISSUE THREAD

**Issue by BalajiSingh** [prashant-ramcharan/courgette-jvm-example#7]
HI Prashant,

Any Plans when are you integrating Courgette with Allure Reports.

With Regards,
Balaji Singh.

**Comment by prashant-ramcharan** [comment]
Hello,

No plans at the moment. I need to investigate if this can be integrated easily within Courgette.

**Comment by prashant-ramcharan** [comment]
Please see example here: https://github.com/prashant-ramcharan/courgette-jvm-allure-example

**Comment by SubhashMsalian** [comment]
How is Node.js different from Javascript?

Subhash M Salian
